name: Create release

on:
  pull_request:
    # types:
    #   - closed
    # branches:
    #   - master

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release and SemVer tag
        id: create-release
        uses: Koenigseder/semver-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: master
          semver-prefix: v
          semver-start-version: 1.0.5
